import {
  existsSync, mkdirSync, writeFileSync, chmodSync,
  readdirSync, statSync, copyFileSync,
} from 'fs';
import { join, dirname, resolve, relative } from 'path';
import { McEnvConfig, ServerProperties } from '../config/schema.js';
import { LockedArtifact } from '../lockfile/schema.js';

export async function setupServerDirectory(
  serverDir: string,
  config: McEnvConfig,
  artifacts: LockedArtifact[],
  configFileDir: string,
): Promise<void> {
  mkdirSync(serverDir, { recursive: true });
  mkdirSync(join(serverDir, 'mods'), { recursive: true });
  mkdirSync(join(serverDir, 'plugins'), { recursive: true });
  mkdirSync(join(serverDir, 'config'), { recursive: true });
  mkdirSync(join(serverDir, 'world'), { recursive: true });
  mkdirSync(join(serverDir, 'logs'), { recursive: true });

  writeEula(serverDir);
  writeServerProperties(serverDir, config.server ?? {}, config.minecraft_version, config);
  writeStartScript(serverDir, config);

  const hasInstaller = artifacts.some((a) => a.dest.endsWith('-installer.jar'));
  if (hasInstaller) writeInstallerReadme(serverDir, config.loader.type);

  // Copy user-managed config files on top of generated ones
  if (config.config_dir) {
    const absConfigDir = resolve(configFileDir, config.config_dir);
    if (existsSync(absConfigDir)) {
      copyConfigDir(absConfigDir, serverDir);
    } else {
      console.warn(`  ⚠  config_dir not found: ${absConfigDir} (skipping)`);
    }
  }

  if (config.hooks?.post_install) {
    console.log(`  ℹ  post_install hook: ${config.hooks.post_install}`);
  }
}

// ── EULA ─────────────────────────────────────────────────────────────────────

function writeEula(serverDir: string): void {
  writeFileSync(
    join(serverDir, 'eula.txt'),
    `# Generated by mcenv\n# https://aka.ms/MinecraftEULA\neula=true\n`,
  );
}

// ── server.properties ────────────────────────────────────────────────────────

/**
 * Full vanilla server.properties with every key documented.
 * Config values override defaults; extra keys in config.server pass through.
 * snake_case keys are automatically converted to kebab-case.
 */
function writeServerProperties(
  serverDir: string,
  props: ServerProperties,
  mcVersion: string,
  config: McEnvConfig,
): void {
  const seed = String(config.world?.seed ?? props.level_seed ?? '');

  const defaults: Record<string, string | number | boolean> = {
    // ── World ──────────────────────────────────────────────────────────────
    'level-name':                       'world',
    'level-seed':                       seed,
    'level-type':                       'minecraft:normal',
    'generator-settings':               '{}',
    'generate-structures':              true,
    'allow-nether':                     true,
    'max-world-size':                   29999984,

    // ── Gameplay ───────────────────────────────────────────────────────────
    'gamemode':                         'survival',
    'force-gamemode':                   false,
    'difficulty':                       'normal',
    'hardcore':                         false,
    'pvp':                              true,
    'spawn-animals':                    true,
    'spawn-monsters':                   true,
    'spawn-npcs':                       true,
    'spawn-protection':                 16,
    'allow-flight':                     false,
    'enable-command-block':             false,
    'function-permission-level':        2,
    'op-permission-level':              4,

    // ── Players ────────────────────────────────────────────────────────────
    'max-players':                      20,
    'online-mode':                      true,
    'white-list':                       false,
    'enforce-whitelist':                false,
    'player-idle-timeout':              0,
    'hide-online-players':              false,
    'enforce-secure-profile':           true,

    // ── Network ────────────────────────────────────────────────────────────
    'server-ip':                        '',
    'server-port':                      25565,
    'network-compression-threshold':    256,
    'prevent-proxy-connections':        false,
    'use-native-transport':             true,
    'rate-limit':                       0,

    // ── Performance ────────────────────────────────────────────────────────
    'view-distance':                    10,
    'simulation-distance':              10,
    'entity-broadcast-range-percentage': 100,
    'max-tick-time':                    60000,
    'max-chained-neighbor-updates':     1000000,
    'sync-chunk-writes':                true,

    // ── Resource pack ──────────────────────────────────────────────────────
    'resource-pack':                    '',
    'resource-pack-sha1':               '',
    'resource-pack-prompt':             '',
    'require-resource-pack':            false,

    // ── RCON / Query ───────────────────────────────────────────────────────
    'enable-rcon':                      false,
    'rcon.port':                        25575,
    'rcon.password':                    '',
    'broadcast-rcon-to-ops':            true,
    'enable-query':                     false,
    'query.port':                       25565,

    // ── Misc ───────────────────────────────────────────────────────────────
    'motd':                             `A Minecraft ${mcVersion} Server`,
    'enable-status':                    true,
    'enable-jmx-monitoring':            false,
    'broadcast-console-to-ops':         true,
    'previews-chat':                    false,
    'text-filtering-config':            '',
    'initial-disabled-packs':           '',
  };

  // Apply config overrides: snake_case → kebab-case
  const merged = { ...defaults };
  for (const [k, v] of Object.entries(props)) {
    if (v === undefined) continue;
    const key = k.replace(/_/g, '-');
    merged[key] = v;
  }

  // Group keys for readability
  const sections: Array<[string, string[]]> = [
    ['World', ['level-name','level-seed','level-type','generator-settings','generate-structures','allow-nether','max-world-size']],
    ['Gameplay', ['gamemode','force-gamemode','difficulty','hardcore','pvp','spawn-animals','spawn-monsters','spawn-npcs','spawn-protection','allow-flight','enable-command-block','function-permission-level','op-permission-level']],
    ['Players', ['max-players','online-mode','white-list','enforce-whitelist','player-idle-timeout','hide-online-players','enforce-secure-profile']],
    ['Network', ['server-ip','server-port','network-compression-threshold','prevent-proxy-connections','use-native-transport','rate-limit']],
    ['Performance', ['view-distance','simulation-distance','entity-broadcast-range-percentage','max-tick-time','max-chained-neighbor-updates','sync-chunk-writes']],
    ['Resource pack', ['resource-pack','resource-pack-sha1','resource-pack-prompt','require-resource-pack']],
    ['RCON / Query', ['enable-rcon','rcon.port','rcon.password','broadcast-rcon-to-ops','enable-query','query.port']],
    ['Misc', ['motd','enable-status','enable-jmx-monitoring','broadcast-console-to-ops','previews-chat','text-filtering-config','initial-disabled-packs']],
  ];

  const written = new Set<string>();
  const lines: string[] = [`# Generated by mcenv ${new Date().toISOString()}`, ''];

  for (const [section, keys] of sections) {
    lines.push(`# ── ${section} ${'─'.repeat(Math.max(0, 60 - section.length))}`);
    for (const k of keys) {
      if (k in merged) {
        lines.push(`${k}=${merged[k]}`);
        written.add(k);
      }
    }
    lines.push('');
  }

  // Any extra keys from config.server that weren't in our template
  const extras = Object.keys(merged).filter((k) => !written.has(k));
  if (extras.length > 0) {
    lines.push('# ── Custom ─────────────────────────────────────────────────────────────');
    for (const k of extras) lines.push(`${k}=${merged[k]}`);
    lines.push('');
  }

  writeFileSync(join(serverDir, 'server.properties'), lines.join('\n'));
}

// ── start.sh ─────────────────────────────────────────────────────────────────

function writeStartScript(serverDir: string, config: McEnvConfig): void {
  const java = config.java ?? {};
  const memory = java.memory ?? '2G';
  const flags = java.flags ?? buildAikarsFlags(memory);
  const javaVersion = java.version ?? '21';
  const needsInstaller = ['forge', 'neoforge', 'quilt'].includes(config.loader.type);

  const installerBlock = needsInstaller ? `
# One-time loader installation (safe to re-run)
INSTALLER="${config.loader.type}-installer.jar"
if [ -f "$INSTALLER" ] && [ ! -f ".loader-installed" ]; then
  echo "Running $INSTALLER …"
  java -jar "$INSTALLER" --installServer
  touch .loader-installed
fi
` : '';

  const preStart = config.hooks?.pre_start
    ? `\n# pre_start hook\n${config.hooks.pre_start}\n`
    : '';

  const script = `#!/bin/bash
# Generated by mcenv — ${config.name}
# Minecraft ${config.minecraft_version} / ${config.loader.type}
# Requires Java ${javaVersion}+

set -e
cd "$(dirname "$0")"
${installerBlock}${preStart}
exec java ${flags.join(' ')} -jar server.jar nogui
`;

  const scriptPath = join(serverDir, 'start.sh');
  writeFileSync(scriptPath, script);
  chmodSync(scriptPath, 0o755);
}

function buildAikarsFlags(memory: string): string[] {
  return [
    `-Xms${memory}`,
    `-Xmx${memory}`,
    '-XX:+UseG1GC',
    '-XX:+ParallelRefProcEnabled',
    '-XX:MaxGCPauseMillis=200',
    '-XX:+UnlockExperimentalVMOptions',
    '-XX:+DisableExplicitGC',
    '-XX:+AlwaysPreTouch',
    '-XX:G1NewSizePercent=30',
    '-XX:G1MaxNewSizePercent=40',
    '-XX:G1HeapRegionSize=8M',
    '-XX:G1ReservePercent=20',
    '-XX:G1HeapWastePercent=5',
    '-XX:G1MixedGCCountTarget=4',
    '-XX:InitiatingHeapOccupancyPercent=15',
    '-XX:G1MixedGCLiveThresholdPercent=90',
    '-XX:G1RSetUpdatingPauseTimePercent=5',
    '-XX:SurvivorRatio=32',
    '-XX:+PerfDisableSharedMem',
    '-XX:MaxTenuringThreshold=1',
    '-Dusing.aikars.flags=https://mcflags.emc.gs',
  ];
}

// ── Config directory copying ──────────────────────────────────────────────────

/**
 * Recursively copy everything from srcDir into destDir.
 * Existing files are overwritten — user configs take precedence over generated ones.
 */
export function copyConfigDir(srcDir: string, destDir: string): void {
  for (const entry of readdirSync(srcDir)) {
    const srcPath = join(srcDir, entry);
    const destPath = join(destDir, entry);
    const stat = statSync(srcPath);
    if (stat.isDirectory()) {
      mkdirSync(destPath, { recursive: true });
      copyConfigDir(srcPath, destPath);
    } else {
      mkdirSync(dirname(destPath), { recursive: true });
      copyFileSync(srcPath, destPath);
    }
  }
}

// ── Loader installer readme ───────────────────────────────────────────────────

function writeInstallerReadme(serverDir: string, loaderType: string): void {
  writeFileSync(
    join(serverDir, 'INSTALL.md'),
    `# ${loaderType} setup\n\nThe start.sh script handles this automatically on first run.\n` +
    `To run manually:\n\n\`\`\`bash\njava -jar ${loaderType}-installer.jar --installServer\n\`\`\`\n`,
  );
}
