import { writeFileSync } from 'fs';
import { join } from 'path';
import { McEnvConfig } from '../config/schema.js';

export function generateDockerfile(serverDir: string, config: McEnvConfig): void {
  const javaVersion = config.java?.version ?? '21';
  const memory = config.java?.memory ?? '2G';
  const loaderType = config.loader.type;
  const isInstaller = loaderType === 'forge' || loaderType === 'neoforge' || loaderType === 'quilt';

  const dockerfile = `# Generated by mcenv ${new Date().toISOString()}
# Minecraft ${config.minecraft_version} / ${loaderType}

FROM eclipse-temurin:${javaVersion}-jre-alpine

LABEL maintainer="mcenv"
LABEL minecraft.version="${config.minecraft_version}"
LABEL minecraft.loader="${loaderType}"

# Create non-root user for security
RUN addgroup -S minecraft && adduser -S minecraft -G minecraft

WORKDIR /server
COPY --chown=minecraft:minecraft . .

${isInstaller ? `# Run installer (Forge/NeoForge/Quilt require this)
RUN java -jar ${loaderType}-installer.jar --installServer && \\
    rm -f ${loaderType}-installer.jar
` : ''}
USER minecraft

EXPOSE 25565

# Aikar's optimized JVM flags
ENV JAVA_FLAGS="-Xms${memory} -Xmx${memory} \\
  -XX:+UseG1GC \\
  -XX:+ParallelRefProcEnabled \\
  -XX:MaxGCPauseMillis=200 \\
  -XX:+UnlockExperimentalVMOptions \\
  -XX:+DisableExplicitGC \\
  -XX:+AlwaysPreTouch \\
  -XX:G1NewSizePercent=30 \\
  -XX:G1MaxNewSizePercent=40 \\
  -XX:G1HeapRegionSize=8M \\
  -XX:G1ReservePercent=20 \\
  -XX:InitiatingHeapOccupancyPercent=15"

VOLUME ["/server/world"]
HEALTHCHECK --interval=30s --timeout=10s --start-period=60s \\
  CMD nc -z localhost 25565 || exit 1

ENTRYPOINT ["sh", "-c", "exec java $JAVA_FLAGS -jar server.jar nogui"]
`;

  writeFileSync(join(serverDir, 'Dockerfile'), dockerfile);
  writeDockerCompose(serverDir, config);
}

function writeDockerCompose(serverDir: string, config: McEnvConfig): void {
  const compose = `# Generated by mcenv
version: '3.8'
services:
  minecraft:
    build: .
    image: mcenv-${config.name}:${config.minecraft_version}
    container_name: ${config.name.replace(/[^a-z0-9-]/gi, '-').toLowerCase()}
    restart: unless-stopped
    ports:
      - "25565:25565"
    volumes:
      - minecraft_world:/server/world
      - minecraft_logs:/server/logs
    environment:
      - JAVA_TOOL_OPTIONS=-Xms${config.java?.memory ?? '2G'} -Xmx${config.java?.memory ?? '2G'}
    stdin_open: true
    tty: true

volumes:
  minecraft_world:
  minecraft_logs:
`;
  writeFileSync(join(serverDir, 'docker-compose.yml'), compose);
}
