/**
 * mcenv init <server-dir>
 *
 * Scans an existing Minecraft server directory and produces:
 *   - mcenv.yaml           (in the current working directory)
 *   - configs/             (mirror of server config files, ready to be managed)
 *
 * Mod identification: every .jar in mods/ and plugins/ is hashed (SHA-512)
 * and looked up against Modrinth's fingerprint API. Unrecognised jars are
 * listed as source: local entries so the config is still complete.
 */

import {
  existsSync, readdirSync, statSync, readFileSync,
  mkdirSync, writeFileSync, createReadStream, copyFileSync,
} from 'fs';
import { join, dirname, basename, extname } from 'path';
import { createHash } from 'crypto';
import yaml from 'js-yaml';
import { fingerprintJars } from '../resolver/modrinth.js';

export interface InitOptions {
  serverDir: string;
  outputDir: string;   // where to write mcenv.yaml and configs/
  name: string;
  dryRun: boolean;
}

export interface InitResult {
  mcVersion: string;
  loaderType: string;
  modCount: number;
  unknownJars: string[];
  configFilesCopied: number;
}

export async function initFromServer(opts: InitOptions): Promise<InitResult> {
  const { serverDir, outputDir, name } = opts;

  if (!existsSync(serverDir)) throw new Error(`Server directory not found: ${serverDir}`);

  // ── Detect Minecraft version and loader ───────────────────────────────────
  const { mcVersion, loaderType, loaderVersion } = detectLoader(serverDir);

  // ── Parse server.properties ───────────────────────────────────────────────
  const serverProps = parseServerProperties(join(serverDir, 'server.properties'));

  // ── Fingerprint jars ──────────────────────────────────────────────────────
  const jarDir = loaderType === 'paper' ? join(serverDir, 'plugins') : join(serverDir, 'mods');
  const jars = existsSync(jarDir)
    ? readdirSync(jarDir).filter((f) => f.endsWith('.jar')).map((f) => join(jarDir, f))
    : [];

  process.stdout.write(`  Hashing ${jars.length} jar(s) … `);
  const hashes = await hashFiles(jars);
  console.log('done');

  process.stdout.write(`  Querying Modrinth fingerprint API … `);
  const hashToSlug = jars.length > 0 ? await fingerprintJars(Object.values(hashes)) : new Map();
  console.log(`${hashToSlug.size}/${jars.length} identified`);

  // Build mod entries
  const modEntries: string[] = [];
  const unknownJars: string[] = [];

  for (const jarPath of jars) {
    const sha512 = hashes[jarPath]!;
    const match = hashToSlug.get(sha512);

    if (match) {
      const isPlugin = loaderType === 'paper';
      modEntries.push(
        `  - id: ${match.slug}\n` +
        `    source: modrinth\n` +
        `    version: "${match.version_number}"`
      );
    } else {
      const filename = basename(jarPath);
      const relPath = loaderType === 'paper'
        ? `plugins/${filename}`
        : `mods/${filename}`;
      unknownJars.push(filename);
      modEntries.push(
        `  # Could not identify on Modrinth — kept as local\n` +
        `  - id: ${basename(filename, extname(filename))}\n` +
        `    source: local\n` +
        `    version: "unknown"\n` +
        `    path: ./${relPath}`
      );
    }
  }

  // ── Copy config files ─────────────────────────────────────────────────────
  const configsDir = join(outputDir, 'configs');
  const configFilesCopied = opts.dryRun ? 0 : copyServerConfigs(serverDir, configsDir, loaderType);

  // ── Build mcenv.yaml ──────────────────────────────────────────────────────
  const modsKey = loaderType === 'paper' ? 'plugins' : 'mods';
  const modBlock = modEntries.length > 0
    ? `\n${modsKey}:\n${modEntries.join('\n\n')}\n`
    : '';

  const javaVersion = detectJavaVersion(serverDir);
  const memoryHint = serverProps['Xmx'] ?? '2G';

  // Build server block from parsed properties
  const serverBlock = buildServerBlock(serverProps);

  const yaml_out = `# Generated by mcenv init from ${serverDir}
# Run: mcenv up
name: ${name}
minecraft_version: "${mcVersion}"

loader:
  type: ${loaderType}${loaderVersion ? `\n  version: "${loaderVersion}"` : ''}

java:
  version: "${javaVersion}"
  memory: "${memoryHint}"

config_dir: ./configs
${serverBlock}${modBlock}`;

  if (!opts.dryRun) {
    mkdirSync(outputDir, { recursive: true });
    writeFileSync(join(outputDir, 'mcenv.yaml'), yaml_out);
  }

  return { mcVersion, loaderType, modCount: jars.length, unknownJars, configFilesCopied };
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function detectLoader(serverDir: string): { mcVersion: string; loaderType: string; loaderVersion?: string } {
  // Check for fabric loader in libraries or version-info files
  const fabricMarker = join(serverDir, '.fabric');
  const paperclipMarker = join(serverDir, 'cache', 'patched_1');
  const versionJson = join(serverDir, 'version.json');

  let mcVersion = 'unknown';
  let loaderType = 'vanilla';
  let loaderVersion: string | undefined;

  // Try version.json (Paper puts one here)
  if (existsSync(versionJson)) {
    try {
      const vj = JSON.parse(readFileSync(versionJson, 'utf8')) as Record<string, unknown>;
      if (typeof vj['id'] === 'string') {
        mcVersion = (vj['id'] as string).match(/^(\d+\.\d+(?:\.\d+)?)/)?.[1] ?? mcVersion;
      }
    } catch { /* ignore */ }
  }

  // Detect from server jar name
  const jarFiles = existsSync(serverDir)
    ? readdirSync(serverDir).filter((f) => f.endsWith('.jar'))
    : [];

  for (const jar of jarFiles) {
    const m = jar.match(/paper-(\d+\.\d+(?:\.\d+)?)-(\d+)\.jar/);
    if (m) { mcVersion = m[1]!; loaderType = 'paper'; break; }

    const fm = jar.match(/fabric-server-mc\.(\d+\.\d+(?:\.\d+)?)-loader\.([\d.]+)/);
    if (fm) { mcVersion = fm[1]!; loaderType = 'fabric'; loaderVersion = fm[2]; break; }

    const vm = jar.match(/minecraft_server\.([\d.]+)\.jar/) ?? jar.match(/server-([\d.]+)\.jar/);
    if (vm) { mcVersion = vm[1]!; loaderType = 'vanilla'; break; }

    const fgm = jar.match(/forge-([\d.]+)-([\d.]+)/);
    if (fgm) { mcVersion = fgm[1]!; loaderType = 'forge'; loaderVersion = fgm[2]; break; }
  }

  // Fallback: look in eula.txt comment or server.properties for clues
  if (mcVersion === 'unknown') {
    const eulaPat = readFilesSafe([join(serverDir, 'eula.txt')]);
    const vMatch = eulaPat.match(/(\d+\.\d+(?:\.\d+)?)/);
    if (vMatch) mcVersion = vMatch[1]!;
  }

  // Fabric marker directory
  if (existsSync(fabricMarker)) loaderType = 'fabric';

  return { mcVersion, loaderType, loaderVersion };
}

function parseServerProperties(filePath: string): Record<string, string> {
  if (!existsSync(filePath)) return {};
  const lines = readFileSync(filePath, 'utf8').split('\n');
  const result: Record<string, string> = {};
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = trimmed.indexOf('=');
    if (idx === -1) continue;
    result[trimmed.slice(0, idx).trim()] = trimmed.slice(idx + 1).trim();
  }
  return result;
}

function buildServerBlock(props: Record<string, string>): string {
  const keys: Array<[string, string]> = [
    ['difficulty', 'difficulty'],
    ['gamemode', 'gamemode'],
    ['max-players', 'max_players'],
    ['online-mode', 'online_mode'],
    ['pvp', 'pvp'],
    ['motd', 'motd'],
    ['level-seed', 'level_seed'],
    ['view-distance', 'view_distance'],
    ['simulation-distance', 'simulation_distance'],
    ['spawn-protection', 'spawn_protection'],
    ['allow-flight', 'allow_flight'],
    ['allow-nether', 'allow_nether'],
    ['white-list', 'white_list'],
    ['enforce-whitelist', 'enforce_whitelist'],
    ['hardcore', 'hardcore'],
    ['enable-command-block', 'enable_command_block'],
    ['server-port', 'server_port'],
    ['enable-rcon', 'enable_rcon'],
  ];

  const lines: string[] = ['server:'];
  for (const [propKey, yamlKey] of keys) {
    const val = props[propKey];
    if (val === undefined || val === '') continue;
    // Quote strings that aren't booleans or numbers
    const needsQuote = isNaN(Number(val)) && val !== 'true' && val !== 'false';
    lines.push(`  ${yamlKey}: ${needsQuote ? `"${val.replace(/"/g, '\\"')}"` : val}`);
  }
  lines.push('');
  return lines.join('\n') + '\n';
}

function detectJavaVersion(serverDir: string): string {
  // Check start.sh for java version hints
  const startSh = readFilesSafe([join(serverDir, 'start.sh'), join(serverDir, 'start.bat')]);
  const m = startSh.match(/java(\d+)|java[- ](\d+)|jdk[- ]?(\d+)/i);
  if (m) return m[1] ?? m[2] ?? m[3] ?? '21';
  return '21';
}

/**
 * Copy config-related directories from the server into the configs/ output dir.
 * Copies: plugins/<name>/config files, config/, and server.properties.
 * Skips: logs/, world/, crash-reports/, jars.
 */
function copyServerConfigs(serverDir: string, configsDir: string, loaderType: string): number {
  mkdirSync(configsDir, { recursive: true });
  let count = 0;

  const SKIP_EXTENSIONS = new Set(['.jar', '.json', '.gz', '.lck', '.tmp']);
  const SKIP_DIRS = new Set(['world', 'world_nether', 'world_the_end', 'logs', 'crash-reports', 'cache', 'libraries', 'versions', '.git', 'mods', 'plugins']);

  function copyEntry(src: string, dest: string): void {
    const stat = statSync(src);
    if (stat.isDirectory()) {
      const dirName = basename(src);
      if (SKIP_DIRS.has(dirName)) return;
      mkdirSync(dest, { recursive: true });
      for (const entry of readdirSync(src)) {
        copyEntry(join(src, entry), join(dest, entry));
      }
    } else {
      if (SKIP_EXTENSIONS.has(extname(src).toLowerCase())) return;
      mkdirSync(dirname(dest), { recursive: true });
      copyFileSync(src, dest);
      count++;
    }
  }

  // Always copy server.properties
  const sp = join(serverDir, 'server.properties');
  if (existsSync(sp)) { copyFileSync(sp, join(configsDir, 'server.properties')); count++; }

  // Copy plugin configs (Paper)
  if (loaderType === 'paper') {
    const pluginsDir = join(serverDir, 'plugins');
    if (existsSync(pluginsDir)) {
      for (const plugin of readdirSync(pluginsDir)) {
        const pluginPath = join(pluginsDir, plugin);
        if (statSync(pluginPath).isDirectory()) {
          copyEntry(pluginPath, join(configsDir, 'plugins', plugin));
        }
      }
    }
  }

  // Copy Fabric/Forge mod configs
  const configDir = join(serverDir, 'config');
  if (existsSync(configDir)) {
    copyEntry(configDir, join(configsDir, 'config'));
  }

  return count;
}

async function hashFiles(paths: string[]): Promise<Record<string, string>> {
  const results: Record<string, string> = {};
  for (const filePath of paths) {
    results[filePath] = await sha512File(filePath);
  }
  return results;
}

function sha512File(filePath: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const hash = createHash('sha512');
    createReadStream(filePath)
      .on('data', (chunk) => hash.update(chunk as Buffer))
      .on('end', () => resolve(hash.digest('hex')))
      .on('error', reject);
  });
}

function readFilesSafe(paths: string[]): string {
  for (const p of paths) {
    if (existsSync(p)) return readFileSync(p, 'utf8');
  }
  return '';
}
